import ResetPasswordTemplate from "@/components/templates/ResetPasswordTemplate";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Recuperar senha",
	description: "Generated by create next app",
};

export default function ResetPasswordPage() {
	return <ResetPasswordTemplate />;
}
