import getAuthorization from "@/utils/getAuthorization";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	if ((await getAuthorization()).success) {
		redirect("/dashboard");
	}

	return (
		<html lang="pt-br">
			<body className={`${inter.className}`}>{children}</body>
		</html>
	);
}
